name: commands
description: A simple Flutter package for wrapping method executions in a Command object
version: 1.0.0
homepage: https://github.com/dustincatap/commands
repository: https://github.com/dustincatap/commands

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.17.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

flutter: null
